package itunes

const (
	AttributeActorTerm         = "actorTerm"
	AttributeGenreIndex        = "genreIndex"
	AttributeArtistTerm        = "artistTerm"
	AttributeShortFilmTerm     = "shortFilmTerm"
	AttributeProducerTerm      = "producerTerm"
	AttributeRatingTerm        = "ratingTerm"
	AttributeDirectorTerm      = "directorTerm"
	AttributeReleaseYearTerm   = "releaseYearTerm"
	AttributeFeatureFilmTerm   = "featureFilmTerm"
	AttributeMovieArtistTerm   = "movieArtistTerm"
	AttributeMovieTerm         = "movieTerm"
	AttributeRatingIndex       = "ratingIndex"
	AttributeDescriptionTerm   = "descriptionTerm"
	AttributeTitleTerm         = "titleTerm"
	AttributeLanguageTerm      = "languageTerm"
	AttributeAuthorTerm        = "authorTerm"
	AttributeKeywordsTerm      = "keywordsTerm"
	AttributeMixTerm           = "mixTerm"
	AttributeComposerTerm      = "composerTerm"
	AttributeAlbumTerm         = "albumTerm"
	AttributeSongTerm          = "songTerm"
	AttributeSoftwareDeveloper = "softwareDeveloper"
	AttributeTvEpisodeTerm     = "tvEpisodeTerm"
	AttributeShowTerm          = "showTerm"
	AttributeTvSeasonTerm      = "tvSeasonTerm"
	AttributeAllArtistTerm     = "allArtistTerm"
	AttributeAllTrackTerm      = "allTrackTerm"
)
