package itunes

type CountryType string

const (
	CountryAD CountryType = "AD" // Andorra
	CountryAE             = "AE" // United Arab Emirates
	CountryAF             = "AF" // Afghanistan
	CountryAG             = "AG" // Antigua and Barbuda
	CountryAI             = "AI" // Anguilla
	CountryAL             = "AL" // Albania
	CountryAM             = "AM" // Armenia
	CountryAO             = "AO" // Angola
	CountryAQ             = "AQ" // Antarctica
	CountryAR             = "AR" // Argentina
	CountryAS             = "AS" // American Samoa
	CountryAT             = "AT" // Austria
	CountryAU             = "AU" // Australia
	CountryAW             = "AW" // Aruba
	CountryAX             = "AX" // Åland Islands
	CountryAZ             = "AZ" // Azerbaijan
	CountryBA             = "BA" // Bosnia and Herzegovina
	CountryBB             = "BB" // Barbados
	CountryBD             = "BD" // Bangladesh
	CountryBE             = "BE" // Belgium
	CountryBF             = "BF" // Burkina Faso
	CountryBG             = "BG" // Bulgaria
	CountryBH             = "BH" // Bahrain
	CountryBI             = "BI" // Burundi
	CountryBJ             = "BJ" // Benin
	CountryBL             = "BL" // Saint Barthélemy
	CountryBM             = "BM" // Bermuda
	CountryBN             = "BN" // Brunei Darussalam
	CountryBO             = "BO" // Bolivia, Plurinational State of
	CountryBQ             = "BQ" // Bonaire, Sint Eustatius and Saba
	CountryBR             = "BR" // Brazil
	CountryBS             = "BS" // Bahamas
	CountryBT             = "BT" // Bhutan
	CountryBV             = "BV" // Bouvet Island
	CountryBW             = "BW" // Botswana
	CountryBY             = "BY" // Belarus
	CountryBZ             = "BZ" // Belize
	CountryCA             = "CA" // Canada
	CountryCC             = "CC" // Cocos  Islands
	CountryCD             = "CD" // Congo, the Democratic Republic of the
	CountryCF             = "CF" // Central African Republic
	CountryCG             = "CG" // Congo
	CountryCH             = "CH" // Switzerland
	CountryCI             = "CI" // Côte d'Ivoire
	CountryCK             = "CK" // Cook Islands
	CountryCL             = "CL" // Chile
	CountryCM             = "CM" // Cameroon
	CountryCN             = "CN" // China
	CountryCO             = "CO" // Colombia
	CountryCR             = "CR" // Costa Rica
	CountryCU             = "CU" // Cuba
	CountryCV             = "CV" // Cabo Verde
	CountryCW             = "CW" // Curaçao
	CountryCX             = "CX" // Christmas Island
	CountryCY             = "CY" // Cyprus
	CountryCZ             = "CZ" // Czechia
	CountryDE             = "DE" // Germany
	CountryDJ             = "DJ" // Djibouti
	CountryDK             = "DK" // Denmark
	CountryDM             = "DM" // Dominica
	CountryDO             = "DO" // Dominican Republic
	CountryDZ             = "DZ" // Algeria
	CountryEC             = "EC" // Ecuador
	CountryEE             = "EE" // Estonia
	CountryEG             = "EG" // Egypt
	CountryEH             = "EH" // Western Sahara
	CountryER             = "ER" // Eritrea
	CountryES             = "ES" // Spain
	CountryET             = "ET" // Ethiopia
	CountryFI             = "FI" // Finland
	CountryFJ             = "FJ" // Fiji
	CountryFK             = "FK" // Falkland
	CountryFM             = "FM" // Micronesia, Federated States of
	CountryFO             = "FO" // Faroe Islands
	CountryFR             = "FR" // France
	CountryGA             = "GA" // Gabon
	CountryGB             = "GB" // United Kingdom of Great Britain and Northern Ireland
	CountryGD             = "GD" // Grenada
	CountryGE             = "GE" // Georgia
	CountryGF             = "GF" // French Guiana
	CountryGG             = "GG" // Guernsey
	CountryGH             = "GH" // Ghana
	CountryGI             = "GI" // Gibraltar
	CountryGL             = "GL" // Greenland
	CountryGM             = "GM" // Gambia
	CountryGN             = "GN" // Guinea
	CountryGP             = "GP" // Guadeloupe
	CountryGQ             = "GQ" // Equatorial Guinea
	CountryGR             = "GR" // Greece
	CountryGS             = "GS" // South Georgia and the South Sandwich Islands
	CountryGT             = "GT" // Guatemala
	CountryGU             = "GU" // Guam
	CountryGW             = "GW" // Guinea-Bissau
	CountryGY             = "GY" // Guyana
	CountryHK             = "HK" // Hong Kong
	CountryHM             = "HM" // Heard Island and McDonald Islands
	CountryHN             = "HN" // Honduras
	CountryHR             = "HR" // Croatia
	CountryHT             = "HT" // Haiti
	CountryHU             = "HU" // Hungary
	CountryID             = "ID" // Indonesia
	CountryIE             = "IE" // Ireland
	CountryIL             = "IL" // Israel
	CountryIM             = "IM" // Isle of Man
	CountryIN             = "IN" // India
	CountryIO             = "IO" // British Indian Ocean Territory
	CountryIQ             = "IQ" // Iraq
	CountryIR             = "IR" // Iran, Islamic Republic of
	CountryIS             = "IS" // Iceland
	CountryIT             = "IT" // Italy
	CountryJE             = "JE" // Jersey
	CountryJM             = "JM" // Jamaica
	CountryJO             = "JO" // Jordan
	CountryJP             = "JP" // Japan
	CountryKE             = "KE" // Kenya
	CountryKG             = "KG" // Kyrgyzstan
	CountryKH             = "KH" // Cambodia
	CountryKI             = "KI" // Kiribati
	CountryKM             = "KM" // Comoros
	CountryKN             = "KN" // Saint Kitts and Nevis
	CountryKP             = "KP" // Korea, Democratic People's Republic of
	CountryKR             = "KR" // Korea, Republic of
	CountryKW             = "KW" // Kuwait
	CountryKY             = "KY" // Cayman Islands
	CountryKZ             = "KZ" // Kazakhstan
	CountryLA             = "LA" // Lao People's Democratic Republic
	CountryLB             = "LB" // Lebanon
	CountryLC             = "LC" // Saint Lucia
	CountryLI             = "LI" // Liechtenstein
	CountryLK             = "LK" // Sri Lanka
	CountryLR             = "LR" // Liberia
	CountryLS             = "LS" // Lesotho
	CountryLT             = "LT" // Lithuania
	CountryLU             = "LU" // Luxembourg
	CountryLV             = "LV" // Latvia
	CountryLY             = "LY" // Libya
	CountryMA             = "MA" // Morocco
	CountryMC             = "MC" // Monaco
	CountryMD             = "MD" // Moldova, Republic of
	CountryME             = "ME" // Montenegro
	CountryMF             = "MF" // Saint Martin (French part)
	CountryMG             = "MG" // Madagascar
	CountryMH             = "MH" // Marshall Islands
	CountryMK             = "MK" // Macedonia, the former Yugoslav Republic of
	CountryML             = "ML" // Mali
	CountryMM             = "MM" // Myanmar
	CountryMN             = "MN" // Mongolia
	CountryMO             = "MO" // Macao
	CountryMP             = "MP" // Northern Mariana Islands
	CountryMQ             = "MQ" // Martinique
	CountryMR             = "MR" // Mauritania
	CountryMS             = "MS" // Montserrat
	CountryMT             = "MT" // Malta
	CountryMU             = "MU" // Mauritius
	CountryMV             = "MV" // Maldives
	CountryMW             = "MW" // Malawi
	CountryMX             = "MX" // Mexico
	CountryMY             = "MY" // Malaysia
	CountryMZ             = "MZ" // Mozambique
	CountryNA             = "NA" // Namibia
	CountryNC             = "NC" // New Caledonia
	CountryNE             = "NE" // Niger
	CountryNF             = "NF" // Norfolk Island
	CountryNG             = "NG" // Nigeria
	CountryNI             = "NI" // Nicaragua
	CountryNL             = "NL" // Netherlands
	CountryNO             = "NO" // Norway
	CountryNP             = "NP" // Nepal
	CountryNR             = "NR" // Nauru
	CountryNU             = "NU" // Niue
	CountryNZ             = "NZ" // New Zealand
	CountryOM             = "OM" // Oman
	CountryPA             = "PA" // Panama
	CountryPE             = "PE" // Peru
	CountryPF             = "PF" // French Polynesia
	CountryPG             = "PG" // Papua New Guinea
	CountryPH             = "PH" // Philippines
	CountryPK             = "PK" // Pakistan
	CountryPL             = "PL" // Poland
	CountryPM             = "PM" // Saint Pierre and Miquelon
	CountryPN             = "PN" // Pitcairn
	CountryPR             = "PR" // Puerto Rico
	CountryPS             = "PS" // Palestine, State of
	CountryPT             = "PT" // Portugal
	CountryPW             = "PW" // Palau
	CountryPY             = "PY" // Paraguay
	CountryQA             = "QA" // Qatar
	CountryRE             = "RE" // Réunion
	CountryRO             = "RO" // Romania
	CountryRS             = "RS" // Serbia
	CountryRU             = "RU" // Russian Federation
	CountryRW             = "RW" // Rwanda
	CountrySA             = "SA" // Saudi Arabia
	CountrySB             = "SB" // Solomon Islands
	CountrySC             = "SC" // Seychelles
	CountrySD             = "SD" // Sudan
	CountrySE             = "SE" // Sweden
	CountrySG             = "SG" // Singapore
	CountrySH             = "SH" // Saint Helena, Ascension and Tristan da Cunha
	CountrySI             = "SI" // Slovenia
	CountrySJ             = "SJ" // Svalbard and Jan Mayen
	CountrySK             = "SK" // Slovakia
	CountrySL             = "SL" // Sierra Leone
	CountrySM             = "SM" // San Marino
	CountrySN             = "SN" // Senegal
	CountrySO             = "SO" // Somalia
	CountrySR             = "SR" // Suriname
	CountrySS             = "SS" // South Sudan
	CountryST             = "ST" // Sao Tome and Principe
	CountrySV             = "SV" // El Salvador
	CountrySX             = "SX" // Sint Maarten (Dutch part)
	CountrySY             = "SY" // Syrian Arab Republic
	CountrySZ             = "SZ" // Swaziland
	CountryTC             = "TC" // Turks and Caicos Islands
	CountryTD             = "TD" // Chad
	CountryTF             = "TF" // French Southern Territories
	CountryTG             = "TG" // Togo
	CountryTH             = "TH" // Thailand
	CountryTJ             = "TJ" // Tajikistan
	CountryTK             = "TK" // Tokelau
	CountryTL             = "TL" // Timor-Leste
	CountryTM             = "TM" // Turkmenistan
	CountryTN             = "TN" // Tunisia
	CountryTO             = "TO" // Tonga
	CountryTR             = "TR" // Turkey
	CountryTT             = "TT" // Trinidad and Tobago
	CountryTV             = "TV" // Tuvalu
	CountryTW             = "TW" // Taiwan, Province of China
	CountryTZ             = "TZ" // Tanzania, United Republic of
	CountryUA             = "UA" // Ukraine
	CountryUG             = "UG" // Uganda
	CountryUM             = "UM" // United States Minor Outlying Islands
	CountryUS             = "US" // United States of America
	CountryUY             = "UY" // Uruguay
	CountryUZ             = "UZ" // Uzbekistan
	CountryVA             = "VA" // Holy See
	CountryVC             = "VC" // Saint Vincent and the Grenadines
	CountryVE             = "VE" // Venezuela, Bolivarian Republic of
	CountryVG             = "VG" // Virgin Islands, British
	CountryVI             = "VI" // Virgin Islands, U.S.
	CountryVN             = "VN" // Viet Nam
	CountryVU             = "VU" // Vanuatu
	CountryWF             = "WF" // Wallis and Futuna
	CountryWS             = "WS" // Samoa
	CountryYE             = "YE" // Yemen
	CountryYT             = "YT" // Mayotte
	CountryZA             = "ZA" // South Africa
	CountryZM             = "ZM" // Zambia
	CountryZW             = "ZW" // Zimbabwe
)
